"""Generate frontend/src/lib/api/catalog-meta.ts from linkable models.

Iterates ``LinkableModel`` subclasses to produce a TypeScript file with:
- CATALOG_META: per-entity record keyed by entity_type, exposing
  entity_type, entity_type_plural, label, and label_plural. Consumed by
  polymorphic frontend code that needs a typed registry of catalog
  entities (e.g. the global changes feed, prop-type narrowing).
- MEDIA_CATEGORIES: per-entity media category lists, keyed by entity_type.

Run via ``make api-gen`` or directly::

    python manage.py export_catalog_meta
"""

from __future__ import annotations

from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

from apps.core.models import LinkableModel


class Command(BaseCommand):
    help = "Generate frontend/src/lib/api/catalog-meta.ts from linkable models."

    def handle(self, **options):
        catalog_meta: list[tuple[str, str, str, str]] = []
        media_categories: dict[str, list[str]] = {}

        for cls in _iter_concrete_subclasses(LinkableModel):
            key = cls.entity_type
            label = cls._meta.verbose_name.title()
            label_plural = cls._meta.verbose_name_plural.title()
            catalog_meta.append((key, cls.entity_type_plural, label, label_plural))
            cats = getattr(cls, "MEDIA_CATEGORIES", [])
            if cats:
                media_categories[key] = list(cats)

        catalog_meta.sort()

        lines = [
            "// Generated by: python manage.py export_catalog_meta",
            "// Do not edit manually.",
            "",
            "export const CATALOG_META = {",
        ]
        for key, plural, label, label_plural in catalog_meta:
            lines.append(f"\t'{key}': {{")
            lines.append(f"\t\tentity_type: '{key}',")
            lines.append(f"\t\tentity_type_plural: '{plural}',")
            lines.append(f"\t\tlabel: '{label}',")
            lines.append(f"\t\tlabel_plural: '{label_plural}',")
            lines.append("\t},")
        lines.append("} as const;")
        lines.append("")
        lines.append("export type CatalogEntityKey = keyof typeof CATALOG_META;")
        lines.append("")
        lines.append("export const MEDIA_CATEGORIES = {")
        for key, cats in sorted(media_categories.items()):
            cats_str = ", ".join(f"'{c}'" for c in cats)
            lines.append(f"\t'{key}': [{cats_str}],")
        lines.append("} as const;")
        lines.append("")

        output_path = (
            Path(settings.BASE_DIR).parent / "frontend/src/lib/api/catalog-meta.ts"
        )
        output_path.write_text("\n".join(lines))
        self.stdout.write(self.style.SUCCESS(f"Wrote {output_path}"))


def _iter_concrete_subclasses(root):
    for cls in root.__subclasses__():
        yield from _iter_concrete_subclasses(cls)
        meta = getattr(cls, "_meta", None)
        if meta is None or meta.abstract:
            continue
        yield cls
