"""Generate frontend/src/lib/entities/relationship-type-meta.ts.

The frontend-relevant half of ``RELATIONSHIP_TYPE_BEHAVIOR`` (see
``apps.catalog.models.model_relationship``): per-``relationship_type`` facts the
related-models editor needs, exported from the backend behavior table so the two
sides can't drift. Today that is just ``requiresMachineTarget`` — whether an edge
of this type must resolve to a seeded machine (no free-text label rung), which
gates the editor's "Describe it" toggle. Behavior lives in the backend table; a
new type joins here automatically and the editor derives its UI rule for free.

Mirrors ``export_citation_type_meta`` / ``export_entity_meta``. Run via
``make codegen`` or directly::

    python manage.py export_relationship_type_meta
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from django.conf import settings
from django.core.management.base import BaseCommand

from apps.catalog.models.model_relationship import (
    RELATIONSHIP_TYPE_BEHAVIOR,
    RelationshipType,
)


class Command(BaseCommand):
    help = "Generate frontend/src/lib/entities/relationship-type-meta.ts."

    def handle(
        self,
        **options: Any,  # noqa: ANN401 - argparse-driven Django command kwargs
    ) -> None:
        # Sorted by value for stable codegen diffs, independent of enum order.
        types = sorted(RelationshipType, key=lambda t: t.value)
        union = " | ".join(f"'{t.value}'" for t in types)

        entries = []
        for t in types:
            body = json.dumps(
                {
                    "key": t.value,
                    "requiresMachineTarget": RELATIONSHIP_TYPE_BEHAVIOR[
                        t
                    ].requires_machine_target,
                },
                indent=2,
            )
            entries.append(f"  {t.value}: {body},")

        lines = [
            "// Generated by: python manage.py export_relationship_type_meta",
            "// Do not edit manually.",
            "",
            "/** The `ModelRelationship.relationship_type` values — the edge kinds. */",
            f"export type RelationshipTypeKey = {union};",
            "",
            "/** Frontend-relevant per-type facts from RELATIONSHIP_TYPE_BEHAVIOR.",
            " * `requiresMachineTarget`: the edge must resolve to a seeded machine",
            " * target (no free-text label rung), so the editor hides the",
            ' * "Describe it" toggle for this type. */',
            "export interface RelationshipTypeMeta {",
            "  key: RelationshipTypeKey;",
            "  requiresMachineTarget: boolean;",
            "}",
            "",
            (
                "export const RELATIONSHIP_TYPE_META: "
                "Record<RelationshipTypeKey, RelationshipTypeMeta> = {"
            ),
            *entries,
            "};",
            "",
        ]

        out_path = (
            Path(settings.BASE_DIR).parent
            / "frontend"
            / "src"
            / "lib"
            / "entities"
            / "relationship-type-meta.ts"
        )
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text("\n".join(lines))
        self.stdout.write(f"Wrote {out_path}")
