"""Generate frontend/src/lib/api/catalog-meta.ts from catalog models.

Iterates ``CatalogModel`` subclasses to produce a TypeScript file with:
- CATALOG_META: per-entity record keyed by entity_type, exposing
  entity_type, entity_type_plural, label, and label_plural. Consumed by
  polymorphic frontend code that needs a typed registry of catalog
  entities (e.g. the global changes feed, prop-type narrowing).
- MEDIA_CATEGORIES: per-entity media category lists, keyed by entity_type.

Run via ``make api-gen`` or directly::

    python manage.py export_catalog_meta
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, NamedTuple

from django.conf import settings
from django.core.management.base import BaseCommand

from apps.catalog._walks import catalog_app_subclasses
from apps.catalog.models import CatalogModel


class CatalogEntry(NamedTuple):
    entity_type: str
    entity_type_plural: str
    label: str
    label_plural: str


class Command(BaseCommand):
    help = "Generate frontend/src/lib/api/catalog-meta.ts from catalog models."

    def handle(
        self,
        **options: Any,  # noqa: ANN401 - argparse-driven Django command kwargs
    ) -> None:
        catalog_meta: list[CatalogEntry] = []
        media_categories: dict[str, list[str]] = {}

        for cls in catalog_app_subclasses(CatalogModel):
            key = cls.entity_type
            label = str(cls._meta.verbose_name).title()
            label_plural = str(cls._meta.verbose_name_plural).title()
            catalog_meta.append(
                CatalogEntry(key, cls.entity_type_plural, label, label_plural)
            )
            cats = getattr(cls, "MEDIA_CATEGORIES", [])
            if cats:
                media_categories[key] = list(cats)

        catalog_meta.sort()

        lines = [
            "// Generated by: python manage.py export_catalog_meta",
            "// Do not edit manually.",
            "",
            "export const CATALOG_META = {",
        ]
        for entry in catalog_meta:
            lines.append(f"\t'{entry.entity_type}': {{")
            lines.append(f"\t\tentity_type: '{entry.entity_type}',")
            lines.append(f"\t\tentity_type_plural: '{entry.entity_type_plural}',")
            lines.append(f"\t\tlabel: '{entry.label}',")
            lines.append(f"\t\tlabel_plural: '{entry.label_plural}',")
            lines.append("\t},")
        lines.append("} as const;")
        lines.append("")
        lines.append("export type CatalogEntityKey = keyof typeof CATALOG_META;")
        lines.append("")
        lines.append("export const MEDIA_CATEGORIES = {")
        for key, cats in sorted(media_categories.items()):
            cats_str = ", ".join(f"'{c}'" for c in cats)
            lines.append(f"\t'{key}': [{cats_str}],")
        lines.append("} as const;")
        lines.append("")

        output_path = (
            Path(settings.BASE_DIR).parent / "frontend/src/lib/api/catalog-meta.ts"
        )
        output_path.write_text("\n".join(lines))
        self.stdout.write(self.style.SUCCESS(f"Wrote {output_path}"))
