"""Generate frontend/src/lib/api/catalog-meta.ts from catalog models.

Introspects Django catalog models to produce a TypeScript file with:
- ENTITY_TYPES: all editable entity types (models with link_url_pattern)
- MEDIA_CATEGORIES: per-entity media category lists

Run via ``make api-gen`` or directly::

    python manage.py export_catalog_meta
"""

from __future__ import annotations

from pathlib import Path

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.management.base import BaseCommand


class Command(BaseCommand):
    help = "Generate frontend/src/lib/api/catalog-meta.ts from catalog models."

    def handle(self, **options):
        entity_types: list[tuple[str, str]] = []
        media_categories: dict[str, list[str]] = {}

        for ct in ContentType.objects.filter(app_label="catalog").order_by("model"):
            model_class = ct.model_class()
            if not model_class or not hasattr(model_class, "link_url_pattern"):
                continue
            entity_types.append((ct.model, model_class._meta.verbose_name.title()))
            cats = getattr(model_class, "MEDIA_CATEGORIES", [])
            if cats:
                media_categories[ct.model] = list(cats)

        lines = [
            "// Generated by: python manage.py export_catalog_meta",
            "// Do not edit manually.",
            "",
            "export const ENTITY_TYPES = [",
        ]
        for value, label in entity_types:
            lines.append(f"  {{ value: '{value}', label: '{label}' }},")
        lines.append("] as const;")
        lines.append("")
        lines.append(
            "export type EntityTypeValue = (typeof ENTITY_TYPES)[number]['value'];"
        )
        lines.append("")
        lines.append("export const MEDIA_CATEGORIES = {")
        for model_name, cats in sorted(media_categories.items()):
            cats_str = ", ".join(f"'{c}'" for c in cats)
            lines.append(f"  {model_name}: [{cats_str}],")
        lines.append("} as const;")
        lines.append("")

        output_path = (
            Path(settings.BASE_DIR).parent / "frontend/src/lib/api/catalog-meta.ts"
        )
        output_path.write_text("\n".join(lines))
        self.stdout.write(self.style.SUCCESS(f"Wrote {output_path}"))
