// Generated by: python manage.py export_catalog_meta
// Do not edit manually.

export const CATALOG_META = {
  cabinet: {
    entity_type: 'cabinet',
    entity_type_plural: 'cabinets',
    label: 'Cabinet',
    label_plural: 'Cabinets',
  },
  'corporate-entity': {
    entity_type: 'corporate-entity',
    entity_type_plural: 'corporate-entities',
    label: 'Corporate Entity',
    label_plural: 'Corporate Entities',
  },
  'credit-role': {
    entity_type: 'credit-role',
    entity_type_plural: 'credit-roles',
    label: 'Credit Role',
    label_plural: 'Credit Roles',
  },
  'display-subtype': {
    entity_type: 'display-subtype',
    entity_type_plural: 'display-subtypes',
    label: 'Display Subtype',
    label_plural: 'Display Subtypes',
  },
  'display-type': {
    entity_type: 'display-type',
    entity_type_plural: 'display-types',
    label: 'Display Type',
    label_plural: 'Display Types',
  },
  franchise: {
    entity_type: 'franchise',
    entity_type_plural: 'franchises',
    label: 'Franchise',
    label_plural: 'Franchises',
  },
  'game-format': {
    entity_type: 'game-format',
    entity_type_plural: 'game-formats',
    label: 'Game Format',
    label_plural: 'Game Formats',
  },
  'gameplay-feature': {
    entity_type: 'gameplay-feature',
    entity_type_plural: 'gameplay-features',
    label: 'Gameplay Feature',
    label_plural: 'Gameplay Features',
  },
  location: {
    entity_type: 'location',
    entity_type_plural: 'locations',
    label: 'Location',
    label_plural: 'Locations',
  },
  manufacturer: {
    entity_type: 'manufacturer',
    entity_type_plural: 'manufacturers',
    label: 'Manufacturer',
    label_plural: 'Manufacturers',
  },
  model: {
    entity_type: 'model',
    entity_type_plural: 'models',
    label: 'Model',
    label_plural: 'Models',
  },
  person: {
    entity_type: 'person',
    entity_type_plural: 'people',
    label: 'Person',
    label_plural: 'People',
  },
  'reward-type': {
    entity_type: 'reward-type',
    entity_type_plural: 'reward-types',
    label: 'Reward Type',
    label_plural: 'Reward Types',
  },
  series: {
    entity_type: 'series',
    entity_type_plural: 'series',
    label: 'Series',
    label_plural: 'Series',
  },
  system: {
    entity_type: 'system',
    entity_type_plural: 'systems',
    label: 'System',
    label_plural: 'Systems',
  },
  tag: {
    entity_type: 'tag',
    entity_type_plural: 'tags',
    label: 'Tag',
    label_plural: 'Tags',
  },
  'technology-generation': {
    entity_type: 'technology-generation',
    entity_type_plural: 'technology-generations',
    label: 'Technology Generation',
    label_plural: 'Technology Generations',
  },
  'technology-subgeneration': {
    entity_type: 'technology-subgeneration',
    entity_type_plural: 'technology-subgenerations',
    label: 'Technology Subgeneration',
    label_plural: 'Technology Subgenerations',
  },
  theme: {
    entity_type: 'theme',
    entity_type_plural: 'themes',
    label: 'Theme',
    label_plural: 'Themes',
  },
  title: {
    entity_type: 'title',
    entity_type_plural: 'titles',
    label: 'Title',
    label_plural: 'Titles',
  },
} as const;

export type CatalogEntityKey = keyof typeof CATALOG_META;

export const MEDIA_CATEGORIES = {
  'gameplay-feature': ['other'],
  manufacturer: ['logo', 'other'],
  model: ['backglass', 'playfield', 'cabinet', 'other'],
  person: ['portrait', 'other'],
} as const;
