// Generated by: python manage.py export_catalog_meta
// Do not edit manually.

export const ENTITY_TYPES = [
	{ value: 'cabinet', label: 'Cabinet' },
	{ value: 'corporateentity', label: 'Corporate Entity' },
	{ value: 'creditrole', label: 'Credit Role' },
	{ value: 'displaysubtype', label: 'Display Subtype' },
	{ value: 'displaytype', label: 'Display Type' },
	{ value: 'franchise', label: 'Franchise' },
	{ value: 'gameformat', label: 'Game Format' },
	{ value: 'gameplayfeature', label: 'Gameplay Feature' },
	{ value: 'model', label: 'Model' },
	{ value: 'manufacturer', label: 'Manufacturer' },
	{ value: 'person', label: 'Person' },
	{ value: 'rewardtype', label: 'Reward Type' },
	{ value: 'series', label: 'Series' },
	{ value: 'system', label: 'System' },
	{ value: 'tag', label: 'Tag' },
	{ value: 'technologygeneration', label: 'Technology Generation' },
	{ value: 'technologysubgeneration', label: 'Technology Subgeneration' },
	{ value: 'theme', label: 'Theme' },
	{ value: 'title', label: 'Title' }
] as const;

export type EntityTypeValue = (typeof ENTITY_TYPES)[number]['value'];

export const MEDIA_CATEGORIES = {
	gameplayfeature: ['other'],
	manufacturer: ['logo', 'other'],
	model: ['backglass', 'playfield', 'cabinet', 'other'],
	person: ['portrait', 'other']
} as const;
