# Generated by Django 6.0.3 on 2026-04-11 22:40

import apps.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("citation", "0001_initial"),
        ("contenttypes", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "input_fingerprint",
                    models.CharField(
                        help_text="Hash of the source data file.", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_default="running",
                        help_text="running — set at creation; a stale running record with an old timestamp indicates a crash. success — transaction committed, all data persisted. failed — exception caught, transaction rolled back.",
                        max_length=10,
                    ),
                ),
                ("records_parsed", models.PositiveIntegerField(db_default=0)),
                ("records_matched", models.PositiveIntegerField(db_default=0)),
                ("records_created", models.PositiveIntegerField(db_default=0)),
                ("claims_asserted", models.PositiveIntegerField(db_default=0)),
                ("claims_retracted", models.PositiveIntegerField(db_default=0)),
                ("claims_rejected", models.PositiveIntegerField(db_default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional free-text note explaining the edit.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who made this edit. Null for source-level changesets.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changesets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingest_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ingest run that produced this changeset. Null for user edits.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changesets",
                        to="provenance.ingestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("wiki", "Wiki"),
                            ("book", "Book"),
                            ("editorial", "Editorial"),
                            ("other", "Other"),
                        ],
                        default="database",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Higher priority wins when claims conflict.",
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disabled sources are excluded from claim resolution.",
                    ),
                ),
                (
                    "default_license",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default license for claims from this source.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="core.license",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.AddField(
            model_name="ingestrun",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingest_runs",
                to="provenance.source",
            ),
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("field_name", models.CharField(max_length=255)),
                (
                    "claim_key",
                    models.CharField(
                        help_text='Identity key for uniqueness. Equals field_name for scalar claims. For relationship claims, encodes the relationship identity (e.g., "credit|person:pat-lawlor|role:art").',
                        max_length=255,
                    ),
                ),
                ("value", models.JSONField()),
                ("citation", models.TextField(blank=True, db_default="", default="")),
                (
                    "is_active",
                    models.BooleanField(
                        db_default=True,
                        default=True,
                        help_text="Current assertion from this author for this claim_key on this subject. False = superseded or retracted.",
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Flag for low-confidence claims that need human review.",
                    ),
                ),
                (
                    "needs_review_notes",
                    models.TextField(
                        blank=True,
                        db_default="",
                        default="",
                        help_text="Context for reviewers about why this claim needs attention.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "changeset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional grouping of claims from a single edit session.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="provenance.changeset",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        help_text="Per-claim license override. Null inherits from source field license or source default.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="core.license",
                    ),
                ),
                (
                    "retracted_by_changeset",
                    models.ForeignKey(
                        blank=True,
                        help_text="The changeset that deactivated this claim (user revert or full_sync retraction).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retracted_claims",
                        to="provenance.changeset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="provenance.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceFieldLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.license",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_licenses",
                        to="provenance.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CitationInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locator",
                    models.TextField(
                        blank=True,
                        db_default="",
                        default="",
                        validators=[apps.core.validators.validate_no_mojibake],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "citation_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="citation.citationsource",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citation_instances",
                        to="provenance.claim",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["citation_source"], name="prov_citinst_source_idx"
                    ),
                    models.Index(fields=["claim"], name="prov_citinst_claim_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="changeset",
            index=models.Index(
                fields=["user", "-created_at"], name="provenance_cs_user_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="changeset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ingest_run__isnull", True), ("user__isnull", False)),
                    models.Q(("ingest_run__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="provenance_changeset_user_xor_ingest_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="provenance_source_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source_type__in",
                        ["database", "wiki", "book", "editorial", "other"],
                    )
                ),
                name="provenance_source_source_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["running", "success", "failed"])),
                name="provenance_ingestrun_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_fingerprint", ""), _negated=True),
                name="provenance_ingestrun_fingerprint_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("finished_at__isnull", True), ("status", "running")),
                    models.Q(
                        models.Q(("status", "running"), _negated=True),
                        ("finished_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="provenance_ingestrun_finished_iff_not_running",
                violation_error_code="cross_field",
                violation_error_message="running requires finished_at=NULL; success/failed requires finished_at to be set.",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["content_type", "object_id", "field_name"],
                name="provenance__content_57ed79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["content_type", "object_id", "claim_key"],
                name="provenance__content_ae6aad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["source", "content_type", "object_id"],
                name="provenance__source__bf9a7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["user", "content_type", "object_id"],
                name="provenance__user_id_779f9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["field_name", "is_active"],
                name="provenance__field_n_5deecd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["source", "is_active"], name="provenance__source__ad9766_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source__isnull", False), ("user__isnull", True)),
                    models.Q(("source__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="provenance_claim_source_xor_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("source__isnull", False)),
                fields=("content_type", "object_id", "source", "claim_key"),
                name="provenance_unique_active_claim_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("user__isnull", False)),
                fields=("content_type", "object_id", "user", "claim_key"),
                name="provenance_unique_active_claim_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.CheckConstraint(
                condition=models.Q(("field_name", ""), _negated=True),
                name="provenance_claim_field_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.CheckConstraint(
                condition=models.Q(("claim_key", ""), _negated=True),
                name="provenance_claim_claim_key_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("retracted_by_changeset__isnull", True),
                    ("is_active", False),
                    _connector="OR",
                ),
                name="provenance_claim_retracted_requires_inactive",
                violation_error_code="cross_field",
                violation_error_message="retracted_by_changeset is only allowed when is_active=False.",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcefieldlicense",
            constraint=models.UniqueConstraint(
                fields=("source", "field_name"),
                name="provenance_sourcefieldlicense_unique_source_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcefieldlicense",
            constraint=models.CheckConstraint(
                condition=models.Q(("field_name", ""), _negated=True),
                name="provenance_sourcefieldlicense_field_name_not_blank",
            ),
        ),
    ]
