# Generated by Django 6.0.3 on 2026-03-18 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("book", "Book"),
                            ("editorial", "Editorial"),
                            ("other", "Other"),
                        ],
                        default="database",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Higher priority wins when claims conflict.",
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("field_name", models.CharField(max_length=255)),
                (
                    "claim_key",
                    models.CharField(
                        default="",
                        help_text='Identity key for uniqueness. Equals field_name for scalar claims. For relationship claims, encodes the relationship identity (e.g., "credit|person:pat-lawlor|role:art").',
                        max_length=255,
                    ),
                ),
                ("value", models.JSONField()),
                ("citation", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="Flag for low-confidence claims that need human review.",
                    ),
                ),
                (
                    "needs_review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Context for reviewers about why this claim needs attention.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="provenance.source",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "field_name"],
                        name="provenance__content_57ed79_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "claim_key"],
                        name="provenance__content_ae6aad_idx",
                    ),
                    models.Index(
                        fields=["source", "content_type", "object_id"],
                        name="provenance__source__bf9a7c_idx",
                    ),
                    models.Index(
                        fields=["user", "content_type", "object_id"],
                        name="provenance__user_id_779f9a_idx",
                    ),
                    models.Index(
                        fields=["field_name", "is_active"],
                        name="provenance__field_n_5deecd_idx",
                    ),
                    models.Index(
                        fields=["source", "is_active"],
                        name="provenance__source__ad9766_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("source__isnull", False), ("user__isnull", True)),
                            models.Q(("source__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="provenance_claim_source_xor_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_active", True), ("source__isnull", False)
                        ),
                        fields=("content_type", "object_id", "source", "claim_key"),
                        name="provenance_unique_active_claim_per_source",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_active", True), ("user__isnull", False)
                        ),
                        fields=("content_type", "object_id", "user", "claim_key"),
                        name="provenance_unique_active_claim_per_user",
                    ),
                ],
            },
        ),
    ]
