# Generated by Django 6.0.3 on 2026-04-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provenance", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="changeset",
            index=models.Index(
                fields=["user", "-created_at"],
                name="provenance_cs_user_created",
            ),
        ),
    ]
