# Generated by Django 6.0.3 on 2026-04-18 12:48

from django.conf import settings
from django.db import migrations, models


def backfill_action(apps, schema_editor):
    """Existing user ChangeSets predate the action column; treat them all as edits.

    All prior user-driven writes in the codebase went through the PATCH
    /claims/ editing endpoints. The revert path uses a separate code path but
    its ChangeSets are semantically still edits in that they assert or retract
    claims; the REVERT action value is used going forward, not backfilled.
    """
    ChangeSet = apps.get_model("provenance", "ChangeSet")
    ChangeSet.objects.filter(user__isnull=False, action__isnull=True).update(
        action="edit"
    )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("provenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="changeset",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("create", "Create"),
                    ("edit", "Edit"),
                    ("delete", "Delete"),
                    ("revert", "Revert"),
                ],
                help_text="What kind of user-driven action this ChangeSet represents. Populated for every user ChangeSet; always NULL for ingest.",
                max_length=8,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_action, noop_reverse),
        migrations.AddIndex(
            model_name="changeset",
            index=models.Index(
                fields=["user", "action", "-created_at"],
                name="provenance_cs_user_action",
            ),
        ),
        migrations.AddConstraint(
            model_name="changeset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("action__isnull", False), ("user__isnull", False)),
                    models.Q(("action__isnull", True), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="provenance_changeset_action_iff_user",
            ),
        ),
    ]
