# Generated by Django 6.0.3 on 2026-04-07 18:16

import apps.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citation", "0001_initial"),
        ("provenance", "0002_add_recent_changes_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locator",
                    models.TextField(
                        blank=True,
                        db_default="",
                        default="",
                        validators=[apps.core.validators.validate_no_mojibake],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "citation_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="citation.citationsource",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citation_instances",
                        to="provenance.claim",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["citation_source"], name="prov_citinst_source_idx"
                    ),
                    models.Index(fields=["claim"], name="prov_citinst_claim_idx"),
                ],
            },
        ),
    ]
