# Generated by Django 6.0.3 on 2026-03-21 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.PositiveBigIntegerField()),
                ("target_id", models.PositiveBigIntegerField()),
                (
                    "source_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="core_record_target__005216_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="core_record_source__a2e30f_idx",
                    ),
                ],
                "unique_together": {
                    ("source_type", "source_id", "target_type", "target_id")
                },
            },
        ),
    ]
