# Generated by Django 6.0.3 on 2026-04-11 22:40

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=500,
                        validators=[apps.core.validators.validate_no_mojibake],
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("magazine", "Magazine"),
                            ("web", "Web"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        validators=[apps.core.validators.validate_no_mojibake],
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        validators=[apps.core.validators.validate_no_mojibake],
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "date_note",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        validators=[apps.core.validators.validate_no_mojibake],
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        validators=[apps.core.validators.validate_no_mojibake],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_default="",
                        default="",
                        validators=[apps.core.validators.validate_no_mojibake],
                    ),
                ),
                (
                    "identifier_key",
                    models.CharField(
                        blank=True,
                        choices=[("ipdb", "IPDB"), ("opdb", "OPDB")],
                        db_default="",
                        default="",
                        help_text="Identifies which URL/ID parsing convention applies to this source's children (e.g. 'ipdb' → numeric machine IDs, 'opdb' → slug IDs). Lives on root sources only; children carry `identifier` instead.",
                        max_length=50,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        db_default="",
                        default="",
                        help_text="Structured identifier for this child source within its parent's scheme (e.g. '4443' for IPDB machine 4443). Empty for root sources and children without structured identifiers.",
                        max_length=200,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="citation.citationsource",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CitationSourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("homepage", "Homepage"),
                            ("catalog", "Catalog"),
                            ("publisher", "Publisher"),
                            ("reference", "Reference"),
                            ("archive", "Archive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        validators=[apps.core.validators.validate_no_mojibake],
                    ),
                ),
                (
                    "citation_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="citation.citationsource",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["citation_source", "link_type", "label"],
            },
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="citation_citationsource_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_type", ""), _negated=True),
                name="citation_citationsource_source_type_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_type__in", ["book", "magazine", "web"])),
                name="citation_citationsource_source_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent__isnull", True),
                    models.Q(("parent", models.F("pk")), _negated=True),
                    _connector="OR",
                ),
                name="citation_citationsource_parent_not_self",
                violation_error_code="cross_field",
                violation_error_message="A citation source cannot be its own parent.",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("year__isnull", True),
                    models.Q(("year__gte", 1800), ("year__lte", 2100)),
                    _connector="OR",
                ),
                name="citation_citationsource_year_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("month__isnull", True),
                    models.Q(("month__gte", 1), ("month__lte", 12)),
                    _connector="OR",
                ),
                name="citation_citationsource_month_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("day__isnull", True),
                    models.Q(("day__gte", 1), ("day__lte", 31)),
                    _connector="OR",
                ),
                name="citation_citationsource_day_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("month__isnull", True), ("year__isnull", False), _connector="OR"
                ),
                name="citation_citationsource_month_requires_year",
                violation_error_code="cross_field",
                violation_error_message="month requires year.",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("day__isnull", True), ("month__isnull", False), _connector="OR"
                ),
                name="citation_citationsource_day_requires_month",
                violation_error_code="cross_field",
                violation_error_message="day requires month.",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("isbn__isnull", True),
                    models.Q(("isbn", ""), _negated=True),
                    _connector="OR",
                ),
                name="citation_citationsource_isbn_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("identifier_key__in", ["", "ipdb", "opdb"])),
                name="citation_citationsource_identifier_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identifier_key", ""), ("parent__isnull", True), _connector="OR"
                ),
                name="citation_citationsource_identifier_key_requires_root",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identifier_key", ""), ("source_type", "web"), _connector="OR"
                ),
                name="citation_citationsource_identifier_key_requires_web",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identifier", ""), ("parent__isnull", False), _connector="OR"
                ),
                name="citation_citationsource_identifier_requires_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identifier__gt", ""), ("identifier_key__gt", ""), _negated=True
                ),
                name="citation_citationsource_identifier_key_or_identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identifier__gt", "")),
                fields=("parent", "identifier"),
                name="citation_citationsource_unique_child_identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsourcelink",
            constraint=models.CheckConstraint(
                condition=models.Q(("url", ""), _negated=True),
                name="citation_citationsourcelink_url_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsourcelink",
            constraint=models.CheckConstraint(
                condition=models.Q(("link_type", ""), _negated=True),
                name="citation_citationsourcelink_link_type_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsourcelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "link_type__in",
                        ["homepage", "catalog", "publisher", "reference", "archive"],
                    )
                ),
                name="citation_citationsourcelink_link_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="citationsourcelink",
            constraint=models.UniqueConstraint(
                fields=("citation_source", "url"),
                name="citation_citationsourcelink_unique_source_url",
            ),
        ),
    ]
