# Generated by Django 6.0.3 on 2026-04-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="citationsource",
            name="identifier_key",
            field=models.CharField(
                blank=True,
                choices=[("ipdb", "IPDB"), ("opdb", "OPDB")],
                db_default="",
                default="",
                help_text="Stable key for frontend identifier parsing dispatch (e.g. 'ipdb', 'opdb').",
                max_length=50,
            ),
        ),
    ]
