# Generated by Django 6.0.3 on 2026-04-10 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citation", "0002_citationsource_identifier_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="citationsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("identifier_key__in", ["", "ipdb", "opdb"])),
                name="citation_citationsource_identifier_key_valid",
            ),
        ),
    ]
