# Generated by Django 6.0.3 on 2026-04-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "citation",
            "0003_citationsource_citation_citationsource_identifier_key_valid",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="citationsource",
            name="identifier_key",
            field=models.CharField(
                blank=True,
                choices=[("ipdb", "IPDB"), ("opdb", "OPDB")],
                db_default="",
                default="",
                help_text="Identifies which URL/ID parsing convention applies to this source's children (e.g. 'ipdb' → numeric machine IDs, 'opdb' → slug IDs). Stopgap: will be subsumed by the extractor registry when the extraction layer is built. See docs/plans/citations/CitationsDesign.md.",
                max_length=50,
            ),
        ),
    ]
