# Generated by Django 6.0.2 on 2026-03-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="CorporateEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Full corporate name, e.g., "D. Gottlieb & Company"',
                        max_length=300,
                    ),
                ),
                (
                    "years_active",
                    models.CharField(
                        blank=True,
                        help_text='Operating period, e.g., "1931-1977"',
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "corporate entity",
                "verbose_name_plural": "corporate entities",
                "ordering": ["manufacturer", "years_active"],
            },
        ),
        migrations.CreateModel(
            name="DisplayType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Franchise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GameFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="GameplayFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "trade_name",
                    models.CharField(
                        blank=True,
                        help_text='Brand name if different (e.g., "Bally" for Midway Manufacturing)',
                        max_length=200,
                    ),
                ),
                (
                    "wikidata_id",
                    models.CharField(
                        blank=True,
                        help_text="Wikidata QID, e.g. Q180268",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("dissolved_year", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "headquarters",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "wikidata_id",
                    models.CharField(
                        blank=True,
                        help_text='Wikidata QID, e.g., "Q312897"',
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Wikidata ID",
                    ),
                ),
                ("birth_year", models.IntegerField(blank=True, null=True)),
                ("birth_month", models.IntegerField(blank=True, null=True)),
                ("birth_day", models.IntegerField(blank=True, null=True)),
                ("death_year", models.IntegerField(blank=True, null=True)),
                ("death_month", models.IntegerField(blank=True, null=True)),
                ("death_day", models.IntegerField(blank=True, null=True)),
                (
                    "birth_place",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("photo_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "people",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="TechnologyGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=255)),
                ("state", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=255)),
                (
                    "corporate_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="catalog.corporateentity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.CreateModel(
            name="DisplaySubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "display_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtypes",
                        to="catalog.displaytype",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="MachineModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "ipdb_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="IPDB ID"
                    ),
                ),
                (
                    "opdb_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="OPDB ID",
                    ),
                ),
                (
                    "pinside_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Pinside ID"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "player_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("production_quantity", models.CharField(blank=True, max_length=100)),
                (
                    "flipper_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "ipdb_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "pinside_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("educational_text", models.TextField(blank=True)),
                ("sources_notes", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "alias_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent machine model if this is a cosmetic/LE variant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases",
                        to="catalog.machinemodel",
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cabinet form factor (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.cabinet",
                    ),
                ),
                (
                    "display_subtype",
                    models.ForeignKey(
                        blank=True,
                        help_text="Display subtype (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.displaysubtype",
                    ),
                ),
                (
                    "display_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Display type (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.displaytype",
                    ),
                ),
                (
                    "game_format",
                    models.ForeignKey(
                        blank=True,
                        help_text="Game format (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.gameformat",
                    ),
                ),
                (
                    "gameplay_features",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Gameplay features (materialized from relationship claims).",
                        related_name="machine_models",
                        to="catalog.gameplayfeature",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="catalog.manufacturer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="corporateentity",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="catalog.manufacturer",
            ),
        ),
        migrations.CreateModel(
            name="DesignCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("design", "Design"),
                            ("art", "Art"),
                            ("mechanics", "Mechanics"),
                            ("music", "Music"),
                            ("sound", "Sound"),
                            ("voice", "Voice"),
                            ("software", "Software"),
                            ("animation", "Dots/Animation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="catalog.machinemodel",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="catalog.person",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="catalog.series",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "person__name"],
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="systems",
                        to="catalog.manufacturer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="machinemodel",
            name="system",
            field=models.ForeignKey(
                blank=True,
                help_text="Hardware system (resolved from system claims).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machine_models",
                to="catalog.system",
            ),
        ),
        migrations.AddField(
            model_name="machinemodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Classification tags (materialized from relationship claims).",
                related_name="machine_models",
                to="catalog.tag",
            ),
        ),
        migrations.AddField(
            model_name="machinemodel",
            name="technology_generation",
            field=models.ForeignKey(
                blank=True,
                help_text="Technology generation (resolved from claims).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machine_models",
                to="catalog.technologygeneration",
            ),
        ),
        migrations.CreateModel(
            name="TechnologySubgeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "technology_generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgenerations",
                        to="catalog.technologygeneration",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.AddField(
            model_name="machinemodel",
            name="themes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Resolved theme tags (materialized from relationship claims).",
                related_name="machine_models",
                to="catalog.theme",
            ),
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opdb_id",
                    models.CharField(
                        help_text='OPDB group ID (e.g., "G5pe4") or synthetic ID (e.g., "ipdb:1234").',
                        max_length=50,
                        unique=True,
                        verbose_name="group ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text='Common abbreviation, e.g., "MM" for Medieval Madness',
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="Title was auto-generated and may need human review.",
                    ),
                ),
                (
                    "needs_review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Context for reviewers about why this title needs attention.",
                    ),
                ),
                (
                    "franchise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="titles",
                        to="catalog.franchise",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="series",
            name="titles",
            field=models.ManyToManyField(
                blank=True, related_name="series", to="catalog.title"
            ),
        ),
        migrations.AddField(
            model_name="machinemodel",
            name="title",
            field=models.ForeignKey(
                blank=True,
                help_text="Title this machine belongs to (resolved from claims).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machine_models",
                to="catalog.title",
            ),
        ),
        migrations.AddConstraint(
            model_name="corporateentity",
            constraint=models.UniqueConstraint(
                fields=("manufacturer", "name"),
                name="catalog_unique_corporate_entity_per_manufacturer",
            ),
        ),
        migrations.AddConstraint(
            model_name="designcredit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("model__isnull", False)),
                fields=("model", "person", "role"),
                name="catalog_unique_credit_per_model_person_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="designcredit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("series__isnull", False)),
                fields=("series", "person", "role"),
                name="catalog_unique_credit_per_series_person_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="designcredit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("model__isnull", False), ("series__isnull", True)),
                    models.Q(("model__isnull", True), ("series__isnull", False)),
                    _connector="OR",
                ),
                name="catalog_credit_model_xor_series",
            ),
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["manufacturer", "year"], name="catalog_mac_manufac_3e73b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["technology_generation", "year"],
                name="catalog_mac_technol_e73054_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["display_type"], name="catalog_mac_display_2a6560_idx"
            ),
        ),
    ]
