# Generated by Django 6.0.3 on 2026-03-21 04:03

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="CorporateEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Full corporate name, e.g., "D. Gottlieb & Company"',
                        max_length=300,
                    ),
                ),
                (
                    "ipdb_manufacturer_id",
                    models.IntegerField(
                        blank=True,
                        help_text="IPDB ManufacturerId for this corporate entity.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "year_start",
                    models.IntegerField(
                        blank=True,
                        help_text="Year this corporate entity was established.",
                        null=True,
                    ),
                ),
                (
                    "year_end",
                    models.IntegerField(
                        blank=True,
                        help_text="Year this corporate entity ceased operations.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "corporate entity",
                "verbose_name_plural": "corporate entities",
                "ordering": ["manufacturer", "year_start"],
            },
        ),
        migrations.CreateModel(
            name="CreditRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="DisplayType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Franchise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GameFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="GameplayFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "opdb_manufacturer_id",
                    models.IntegerField(
                        blank=True,
                        help_text="OPDB manufacturer_id for this brand.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "wikidata_id",
                    models.CharField(
                        blank=True,
                        help_text="Wikidata QID, e.g. Q180268",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("website", models.URLField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "wikidata_id",
                    models.CharField(
                        blank=True,
                        help_text='Wikidata QID, e.g., "Q312897"',
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Wikidata ID",
                    ),
                ),
                ("birth_year", models.IntegerField(blank=True, null=True)),
                ("birth_month", models.IntegerField(blank=True, null=True)),
                ("birth_day", models.IntegerField(blank=True, null=True)),
                ("death_year", models.IntegerField(blank=True, null=True)),
                ("death_month", models.IntegerField(blank=True, null=True)),
                ("death_day", models.IntegerField(blank=True, null=True)),
                (
                    "birth_place",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("photo_url", models.URLField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "people",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="TechnologyGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=255)),
                ("state", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=255)),
                (
                    "corporate_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="catalog.corporateentity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.CreateModel(
            name="DisplaySubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "display_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtypes",
                        to="catalog.displaytype",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.AddField(
            model_name="corporateentity",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="catalog.manufacturer",
            ),
        ),
        migrations.CreateModel(
            name="TechnologySubgeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "technology_generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgenerations",
                        to="catalog.technologygeneration",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="systems",
                        to="catalog.manufacturer",
                    ),
                ),
                (
                    "technology_subgeneration",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technology subgeneration this system belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="systems",
                        to="catalog.technologysubgeneration",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "parents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Parent themes in the hierarchy (structural, not claim-controlled).",
                        related_name="children",
                        to="catalog.theme",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opdb_id",
                    models.CharField(
                        blank=True,
                        help_text='OPDB group ID (e.g., "G5pe4"). Null for titles without an OPDB group.',
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="OPDB group ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "fandom_page_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Fandom wiki page ID for deep-linking.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="Title was auto-generated and may need human review.",
                    ),
                ),
                (
                    "needs_review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Context for reviewers about why this title needs attention.",
                    ),
                ),
                (
                    "franchise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="titles",
                        to="catalog.franchise",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "titles",
                    models.ManyToManyField(
                        blank=True, related_name="series", to="catalog.title"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MachineModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "ipdb_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="IPDB ID"
                    ),
                ),
                (
                    "opdb_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="OPDB ID",
                    ),
                ),
                (
                    "pinside_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Pinside ID"
                    ),
                ),
                (
                    "is_conversion",
                    models.BooleanField(
                        default=False,
                        help_text="True if this machine is a conversion/retheme (resolved from claims).",
                    ),
                ),
                (
                    "is_remake",
                    models.BooleanField(
                        default=False,
                        help_text="True if this machine is a remake of an earlier model (resolved from claims).",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "player_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("production_quantity", models.CharField(blank=True, max_length=100)),
                (
                    "flipper_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "ipdb_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "pinside_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "cabinet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cabinet form factor (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.cabinet",
                    ),
                ),
                (
                    "converted_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source machine if this is a conversion/retheme (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="catalog.machinemodel",
                    ),
                ),
                (
                    "corporate_entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific corporate incarnation that produced this model (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="models",
                        to="catalog.corporateentity",
                    ),
                ),
                (
                    "display_subtype",
                    models.ForeignKey(
                        blank=True,
                        help_text="Display subtype (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.displaysubtype",
                    ),
                ),
                (
                    "display_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Display type (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.displaytype",
                    ),
                ),
                (
                    "game_format",
                    models.ForeignKey(
                        blank=True,
                        help_text="Game format (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.gameformat",
                    ),
                ),
                (
                    "gameplay_features",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Gameplay features (materialized from relationship claims).",
                        related_name="machine_models",
                        to="catalog.gameplayfeature",
                    ),
                ),
                (
                    "remake_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original model if this is a remake (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remakes",
                        to="catalog.machinemodel",
                    ),
                ),
                (
                    "variant_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent machine model if this is a cosmetic/LE variant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants",
                        to="catalog.machinemodel",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hardware system (resolved from system claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.system",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Classification tags (materialized from relationship claims).",
                        related_name="machine_models",
                        to="catalog.tag",
                    ),
                ),
                (
                    "technology_generation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technology generation (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.technologygeneration",
                    ),
                ),
                (
                    "technology_subgeneration",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technology subgeneration (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.technologysubgeneration",
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Resolved theme tags (materialized from relationship claims).",
                        related_name="machine_models",
                        to="catalog.theme",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        help_text="Title this machine belongs to (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.title",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TitleAbbreviation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=50)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abbreviations",
                        to="catalog.title",
                    ),
                ),
            ],
            options={
                "ordering": ["value"],
            },
        ),
        migrations.CreateModel(
            name="ManufacturerAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=200)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.manufacturer",
                    ),
                ),
            ],
            options={
                "ordering": ["value"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("value"),
                        name="catalog_unique_manufacturer_alias_lower",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelAbbreviation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=50)),
                (
                    "machine_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abbreviations",
                        to="catalog.machinemodel",
                    ),
                ),
            ],
            options={
                "ordering": ["value"],
                "unique_together": {("machine_model", "value")},
            },
        ),
        migrations.CreateModel(
            name="PersonAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=200)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.person",
                    ),
                ),
            ],
            options={
                "ordering": ["value"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("value"),
                        name="catalog_unique_person_alias_lower",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="catalog.creditrole",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="catalog.machinemodel",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="catalog.person",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="catalog.series",
                    ),
                ),
            ],
            options={
                "ordering": ["role__display_order", "person__name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("model__isnull", False)),
                        fields=("model", "person", "role"),
                        name="catalog_unique_credit_per_model_person_role",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("series__isnull", False)),
                        fields=("series", "person", "role"),
                        name="catalog_unique_credit_per_series_person_role",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("model__isnull", False), ("series__isnull", True)
                            ),
                            models.Q(
                                ("model__isnull", True), ("series__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="catalog_credit_model_xor_series",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemMpuString",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=200)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpu_strings",
                        to="catalog.system",
                    ),
                ),
            ],
            options={
                "ordering": ["value"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("value",), name="catalog_unique_system_mpu_string"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ThemeAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=200)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.theme",
                    ),
                ),
            ],
            options={
                "ordering": ["value"],
                "unique_together": {("theme", "value")},
            },
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["corporate_entity", "year"],
                name="catalog_mac_corpora_e8a031_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["technology_generation", "year"],
                name="catalog_mac_technol_e73054_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["display_type"], name="catalog_mac_display_2a6560_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="titleabbreviation",
            unique_together={("title", "value")},
        ),
    ]
