# Generated by Django 6.0.3 on 2026-04-11 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machinemodel",
            options={
                "ordering": ["name"],
                "verbose_name": "model",
                "verbose_name_plural": "models",
            },
        ),
    ]
