# Generated by Django 6.0.3 on 2026-03-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinemodel",
            name="technology_subgeneration",
            field=models.ForeignKey(
                blank=True,
                help_text="Technology subgeneration (resolved from claims).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machine_models",
                to="catalog.technologysubgeneration",
            ),
        ),
    ]
