# Generated by Django 6.0.3 on 2026-04-28 08:33

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_creditrole_machine_models_creditrole_series_credited'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateentitylocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='corporateentitylocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
