# Generated by Django 6.0.3 on 2026-04-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_corporateentitylocation_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'slug'), name='catalog_location_unique_slug_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('slug',), name='catalog_location_unique_slug_at_root'),
        ),
    ]
