# Generated by Django 6.0.3 on 2026-04-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_slugs_lowercase_and_name_unique_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='corporate_entities',
            field=models.ManyToManyField(related_name='+', through='catalog.CorporateEntityLocation', to='catalog.corporateentity'),
        ),
    ]
