# Generated by Django 6.0.3 on 2026-04-11 22:40

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("processing", "Processing"),
                            ("failed", "Failed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EntityMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveBigIntegerField()),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["content_type", "object_id", "-is_primary", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaRendition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "rendition_type",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("thumb", "Thumbnail"),
                            ("display", "Display"),
                        ],
                        max_length=30,
                    ),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("is_ready", models.BooleanField(default=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renditions",
                        to="media.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset", "rendition_type"],
            },
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_filename", ""), _negated=True),
                name="media_mediaasset_original_filename_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("mime_type", ""), _negated=True),
                name="media_mediaasset_mime_type_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_filename__contains", ".")),
                name="media_mediaasset_original_filename_has_ext",
                violation_error_message="original_filename must contain a file extension.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("byte_size__gt", 0)),
                name="media_mediaasset_byte_size_positive",
                violation_error_message="byte_size must be greater than zero.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["image", "video"])),
                name="media_mediaasset_kind_valid",
                violation_error_message="kind must be 'image' or 'video'.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ready", "processing", "failed"])),
                name="media_mediaasset_status_valid",
                violation_error_message="status must be 'ready', 'processing', or 'failed'.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("height__isnull", True), ("width__isnull", True)),
                    models.Q(("height__isnull", False), ("width__isnull", False)),
                    _connector="OR",
                ),
                name="media_mediaasset_dimensions_both_or_neither",
                violation_error_code="cross_field",
                violation_error_message="width and height must both be null or both be set.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("width__isnull", True), ("width__gt", 0), _connector="OR"
                ),
                name="media_mediaasset_width_positive",
                violation_error_message="width must be greater than zero.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("height__isnull", True), ("height__gt", 0), _connector="OR"
                ),
                name="media_mediaasset_height_positive",
                violation_error_message="height must be greater than zero.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "image"), ("status", "ready"), _negated=True),
                    ("width__isnull", False),
                    _connector="OR",
                ),
                name="media_mediaasset_ready_image_has_dimensions",
                violation_error_code="cross_field",
                violation_error_message="A ready image must have width and height.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "image"), _negated=True),
                    models.Q(("status", "processing"), _negated=True),
                    _connector="OR",
                ),
                name="media_mediaasset_image_not_processing",
                violation_error_code="cross_field",
                violation_error_message="Images are processed synchronously and cannot have status 'processing'.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "image"), ("mime_type__startswith", "image/")),
                    models.Q(("kind", "video"), ("mime_type__startswith", "video/")),
                    _connector="OR",
                ),
                name="media_mediaasset_mime_type_matches_kind",
                violation_error_code="cross_field",
                violation_error_message="mime_type must be consistent with kind.",
            ),
        ),
        migrations.AddIndex(
            model_name="entitymedia",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="media_entitymedia_entity_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymedia",
            constraint=models.UniqueConstraint(
                fields=("asset",), name="media_entitymedia_unique_asset"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("category__isnull", False), ("is_primary", True)),
                fields=("content_type", "object_id", "category"),
                name="media_entitymedia_one_primary_per_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("category__isnull", True), ("is_primary", True)),
                fields=("content_type", "object_id"),
                name="media_entitymedia_one_primary_uncategorized",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymedia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("category__isnull", True),
                    models.Q(("category", ""), _negated=True),
                    _connector="OR",
                ),
                name="media_entitymedia_category_not_blank",
                violation_error_message="category must be null or non-empty.",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymedia",
            constraint=models.CheckConstraint(
                condition=models.Q(("object_id__gt", 0)),
                name="media_entitymedia_object_id_positive",
                violation_error_message="object_id must be greater than zero.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediarendition",
            constraint=models.CheckConstraint(
                condition=models.Q(("rendition_type", ""), _negated=True),
                name="media_mediarendition_rendition_type_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediarendition",
            constraint=models.CheckConstraint(
                condition=models.Q(("mime_type", ""), _negated=True),
                name="media_mediarendition_mime_type_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediarendition",
            constraint=models.CheckConstraint(
                condition=models.Q(("byte_size__gt", 0)),
                name="media_mediarendition_byte_size_positive",
                violation_error_message="byte_size must be greater than zero.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediarendition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("height__isnull", True), ("width__isnull", True)),
                    models.Q(("height__isnull", False), ("width__isnull", False)),
                    _connector="OR",
                ),
                name="media_mediarendition_dimensions_both_or_neither",
                violation_error_code="cross_field",
                violation_error_message="width and height must both be null or both be set.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediarendition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("width__isnull", True), ("width__gt", 0), _connector="OR"
                ),
                name="media_mediarendition_width_positive",
                violation_error_message="width must be greater than zero.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediarendition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("height__isnull", True), ("height__gt", 0), _connector="OR"
                ),
                name="media_mediarendition_height_positive",
                violation_error_message="height must be greater than zero.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediarendition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rendition_type__in", ["original", "thumb", "display"])
                ),
                name="media_mediarendition_rendition_type_valid",
                violation_error_message="rendition_type must be 'original', 'thumb', or 'display'.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediarendition",
            constraint=models.UniqueConstraint(
                fields=("asset", "rendition_type"),
                name="media_mediarendition_unique_asset_rendition_type",
            ),
        ),
    ]
