"""Generate frontend/src/lib/citation-types/citation-type-meta.ts.

The declarative half of the citation-type plugin channel: per-type facts the frontend
locator UX reads — label, locator kind, placeholder, invalid message,
child-skips flag, and slug-addressed flag — exported from the backend registry
so the two sides can't drift. Behavior (the client-side grammar mirror, UX-only)
lives in the hand-written per-type modules beside the generated file; their
registry asserts exhaustiveness against the generated key union at compile
time.

Run via ``make codegen`` or directly::

    python manage.py export_citation_type_meta
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, override

from django.conf import settings
from django.core.management.base import BaseCommand

from apps.citation.citation_types import CITATION_TYPE_SPECS


class Command(BaseCommand):
    help = "Generate frontend/src/lib/citation-types/citation-type-meta.ts."

    @override
    def handle(
        self,
        **options: Any,
    ) -> None:
        # Sorted by key for stable codegen diffs, independent of registration
        # order (which is load-bearing for recognition, not for display).
        specs = sorted(CITATION_TYPE_SPECS.values(), key=lambda s: s.source_type)
        keys = [str(spec.source_type.value) for spec in specs]
        union = " | ".join(f"'{k}'" for k in keys)

        entries = []
        for spec in specs:
            body = json.dumps(
                {
                    "key": spec.source_type.value,
                    "label": spec.source_type.label,
                    "locatorKind": spec.locator.kind,
                    "locatorLabel": spec.locator.label,
                    "locatorPlaceholder": spec.locator.placeholder,
                    "locatorHelp": spec.locator.help,
                    "locatorDisplayPrefix": spec.locator.display_prefix,
                    "locatorInvalidMessage": spec.locator.invalid_message,
                    "childSkipsLocator": spec.child_skips_locator,
                    "slugAddressed": spec.slug_addressed,
                    "childNounPlural": spec.child_noun_plural,
                    "authoredRootCreation": spec.authored_root_creation,
                },
                indent=2,
            )
            entries.append(f"  {spec.source_type.value}: {body},")

        lines = [
            "// Generated by: python manage.py export_citation_type_meta",
            "// Do not edit manually.",
            "",
            "/** The registered citation-type keys (`CitationSource.source_type` values). */",
            f"export type CitationTypeKey = {union};",
            "",
            "/** Declarative per-type facts, exported from the backend registry.",
            " * `locatorKind` is the frontend input behavior: `freeform` is a plain",
            " * text input; `timestamp` adds the type's inline validation.",
            " * `locatorLabel`/`locatorHelp` are the field label and persistent",
            " * format guidance the cite picker shows (not placeholder text).",
            " * `locatorDisplayPrefix` prefixes the locator on the read side",
            " * (tooltip, references) — e.g. video's `starting at` prefix.",
            " * `slugAddressed` marks types addressed by an authored kebab slug",
            " * (periodical issues) — the create UI shows a slug field for these.",
            " * `childNounPlural` is what the type's children are called in UI",
            " * copy (a periodical's 'issues') — display vocabulary only.",
            " * `authoredRootCreation` marks types whose roots may be created",
            " * through the authored-create form — the create-stage type picker",
            " * offers exactly these. */",
            "export interface CitationTypeMeta {",
            "  key: CitationTypeKey;",
            "  label: string;",
            "  locatorKind: 'freeform' | 'timestamp';",
            "  locatorLabel: string;",
            "  locatorPlaceholder: string;",
            "  locatorHelp: string;",
            "  locatorDisplayPrefix: string;",
            "  locatorInvalidMessage: string;",
            "  childSkipsLocator: boolean;",
            "  slugAddressed: boolean;",
            "  childNounPlural: string;",
            "  authoredRootCreation: boolean;",
            "}",
            "",
            "export const CITATION_TYPE_META: Record<CitationTypeKey, CitationTypeMeta> = {",
            *entries,
            "};",
            "",
        ]

        out_path = (
            Path(settings.BASE_DIR).parent
            / "frontend"
            / "src"
            / "lib"
            / "citation-types"
            / "citation-type-meta.ts"
        )
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text("\n".join(lines))
        self.stdout.write(f"Wrote {out_path}")
