"""Generate scripts/analysis/sql/shared_hosts.sql from the shared-host table.

The analytics layer's copy of :data:`~apps.citation.shared_hosts.SHARED_HOSTS`.
One DuckDB view, ``shared_hosts``: the declared host and its platform label.
Only the table is generated. The label-boundary suffix rule stays hand-written
in ``provenance.sql`` (``_shared_cdn_host``), where it sits beside the other
mirrors of this module's matching vocabulary — what drifted was the list, and
a list is the part SQL cannot derive for itself.

Generated rather than retyped because the declaration is Python with no
database row behind it, so nothing in SQL could read it at query time and a
hand-kept copy has no way to notice it has fallen behind.

Run via ``make codegen``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

from apps.citation.shared_hosts import SHARED_HOSTS

OUTPUT_PATH = "scripts/analysis/sql/shared_hosts.sql"


def _sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _rows() -> list[tuple[str, str]]:
    """Every declared (host, label), sorted by host for stable codegen diffs."""
    return sorted((host, spec.label) for spec in SHARED_HOSTS for host in spec.hosts)


def _view(rows: list[tuple[str, str]]) -> list[str]:
    width = max(len(_sql_str(host)) for host, _ in rows)
    lines = [
        "CREATE OR REPLACE VIEW shared_hosts AS",
        "  SELECT * FROM (VALUES",
    ]
    for i, (host, label) in enumerate(rows):
        tail = "" if i == len(rows) - 1 else ","
        lines.append(f"    ({_sql_str(host).ljust(width)}, {_sql_str(label)}){tail}")
    lines += [
        "  ) AS t(host, label);",
        "COMMENT ON VIEW shared_hosts IS",
        (
            "  'One row per declared shared multi-tenant host — the host and the platform"
            " that serves tenants on it. The widest honest host, matched by label-boundary"
            " suffix: a URL is on a shared host when its host equals or ends in one of"
            " these. Recognition there is path-scoped, so citation_root_for_host() returns"
            " NULL and only citation_root_for_url() can attribute a tenant.';"
        ),
    ]
    return lines


class Command(BaseCommand):
    help = f"Generate {OUTPUT_PATH} from the shared-host table."

    def handle(
        self,
        **options: Any,  # noqa: ANN401 - argparse-driven Django command kwargs
    ) -> None:
        rows = _rows()
        # An empty table would generate a view that reports every host ordinary,
        # which is the silent direction: bare rows would become eligible again.
        if not rows:
            raise CommandError("SHARED_HOSTS declares no hosts.")

        lines = [
            "-- ═══ §170 SHARED HOSTS — hosts that need a tenant path to attribute ════════",
            "-- Generated by: python manage.py export_shared_hosts",
            "-- Do not edit manually — edit apps/citation/shared_hosts.py and re-run",
            "-- `make codegen`.",
            "--",
            "-- A shared host serves many unrelated publishers' files under one hostname,",
            "-- the owning tenant named only by a path segment (a GoDaddy site's documents",
            "-- on img1.wsimg.com/blobby/go/<uuid>, a maker's own facebook.com page). Host-",
            "-- only recognition cannot attribute such a URL, so recognition there is",
            "-- path-scoped and a bare registration is refused.",
            "--",
            "-- Generated because the declaration is Python with no database row behind it:",
            "-- nothing in SQL can read it at query time, and a hand-kept copy has no way to",
            "-- notice it has fallen behind. It did fall behind once, and the loud half was a",
            "-- check firing on a legitimate path-scoped row. The silent half is the one that",
            "-- matters — a host this layer thinks is ordinary keeps its bare row eligible,",
            "-- so citation_root_for_url() attributes every tenant's URL to whoever",
            "-- registered the host, disagreeing with what the app itself resolves.",
            "",
            *_view(rows),
            "",
        ]

        output_path = Path(settings.BASE_DIR).parent / OUTPUT_PATH
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines))
